"""
Fix Planner - PR3

Generate fix plans from diagnostics.
Only generates S1 (safe) patches.
Preserves alias/embed/fragment structure.
"""

from __future__ import annotations

import json
import difflib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from obc.resolver import Diagnostic, DiagnosticCode


@dataclass
class FixCandidate:
    """A candidate fix for a diagnostic."""
    diagnostic: Diagnostic
    safety_level: str

    # The patch
    old_text: str
    new_text: str
    source_file: Path
    line: int

    # Evidence
    reason: str
    target_path: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "safety_level": self.safety_level,
            "old_text": self.old_text,
            "new_text": self.new_text,
            "source_file": str(self.source_file),
            "line": self.line,
            "reason": self.reason,
            "target_path": self.target_path,
        }


@dataclass
class FixPlan:
    """A complete fix plan."""
    version: str = "1.0"
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    vault: str = ""
    total_diagnostics: int = 0
    total_candidates: int = 0

    # Grouped by safety
    safe_fixes: list[FixCandidate] = field(default_factory=list)
    review_fixes: list[FixCandidate] = field(default_factory=list)

    # Broken links without fix candidates
    unfixable: list[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "version": self.version,
            "created_at": self.created_at,
            "vault": self.vault,
            "summary": {
                "total_diagnostics": self.total_diagnostics,
                "total_candidates": self.total_candidates,
                "safe_fixes": len(self.safe_fixes),
                "review_fixes": len(self.review_fixes),
                "unfixable": len(self.unfixable),
            },
            "safe_fixes": [f.to_dict() for f in self.safe_fixes],
            "review_fixes": [f.to_dict() for f in self.review_fixes],
            "unfixable": self.unfixable,
        }

    def to_patch(self) -> str:
        """Generate unified diff format patch."""
        patches = []
        patches.append("--- a/vault")
        patches.append("+++ b/vault")
        patches.append(f"@@ Generated by OBC at {self.created_at} @@")

        # Group by file
        by_file: dict[Path, list[FixCandidate]] = {}
        for fix in self.safe_fixes:
            if fix.source_file not in by_file:
                by_file[fix.source_file] = []
            by_file[fix.source_file].append(fix)

        for file_path, fixes in by_file.items():
            patches.append(f"--- {file_path}")
            patches.append(f"+++ {file_path}")

            for fix in fixes:
                # Calculate hunk header
                old_lines = fix.old_text.split('\n')
                new_lines = fix.new_text.split('\n')

                context = 2
                old_start = max(1, fix.line - context)
                old_count = len(old_lines) + context
                new_count = len(new_lines) + context

                patches.append(f"@@ -{old_start},{old_count} +1,{new_count} @@")

                for line in old_lines:
                    patches.append(f"-{line}")
                for line in new_lines:
                    patches.append(f"+{line}")

        return '\n'.join(patches)


class FixPlanner:
    """
    Generate fix plans from diagnostics.

    Safety levels:
    - S1: Safe - exact failure + single candidate + structure preserved
    - S2: Review - multiple candidates or fuzzy match
    - S3: Never - unsupported or destructive

    Only S1 patches are generated by default.
    """

    def __init__(self):
        pass

    def plan(self, diagnostics: list[Diagnostic], vault: str = "") -> FixPlan:
        """
        Generate a fix plan from diagnostics.

        Args:
            diagnostics: List of diagnostics to plan fixes for
            vault: Vault path for reference

        Returns:
            FixPlan with candidate fixes
        """
        plan = FixPlan(vault=vault, total_diagnostics=len(diagnostics))

        for diag in diagnostics:
            candidate = self._plan_fix(diag)

            if candidate:
                if candidate.safety_level == "S1":
                    plan.safe_fixes.append(candidate)
                else:
                    plan.review_fixes.append(candidate)
            else:
                # No fix possible
                if diag.code not in (DiagnosticCode.OK_EXACT,
                                     DiagnosticCode.OK_UNIQUE_BY_BASENAME,
                                     DiagnosticCode.OK_WITH_FRAGMENT,
                                     DiagnosticCode.IGNORED_EXTERNAL):
                    plan.unfixable.append({
                        "code": diag.code.value,
                        "source_file": str(diag.link.source_file),
                        "line": diag.link.line,
                        "raw_text": diag.link.raw_text,
                        "message": diag.message,
                    })

        plan.total_candidates = len(plan.safe_fixes) + len(plan.review_fixes)
        return plan

    def _plan_fix(self, diag: Diagnostic) -> Optional[FixCandidate]:
        """
        Plan a fix for a single diagnostic.

        Only broken links need fixes. OK_* diagnostics don't need fixing.
        """
        link = diag.link

        # OK_* codes don't need fixes
        ok_codes = (DiagnosticCode.OK_EXACT, DiagnosticCode.OK_UNIQUE_BY_BASENAME,
                    DiagnosticCode.OK_WITH_FRAGMENT, DiagnosticCode.IGNORED_EXTERNAL)
        if diag.code in ok_codes:
            return None

        # Only plan fixes with candidates or suggestions
        if not diag.candidates and not diag.suggested_fix:
            return None

        # S1: Single candidate
        if diag.safety_level == "S1" and diag.candidates:
            target = diag.candidates[0]
            new_text = self._build_safe_link(link, target.normalized_path)
            return FixCandidate(
                diagnostic=diag,
                safety_level="S1",
                old_text=link.raw_text,
                new_text=new_text,
                source_file=link.source_file,
                line=link.line,
                reason="Unique deterministic candidate",
                target_path=target.normalized_path,
            )

        # S2: Multiple candidates or suggestion
        if diag.safety_level in ("S1", "S2") and (diag.candidates or diag.suggested_fix):
            target_path = diag.candidates[0].normalized_path if diag.candidates else diag.suggested_fix
            new_text = self._build_safe_link(link, target_path)
            return FixCandidate(
                diagnostic=diag,
                safety_level=diag.safety_level,
                old_text=link.raw_text,
                new_text=new_text,
                source_file=link.source_file,
                line=link.line,
                reason=diag.message,
                target_path=target_path,
            )

        return None

    def _build_safe_link(self, link, target_path: str) -> str:
        """
        Build a safe link that preserves alias/fragment structure.

        Always preserves the original link format.
        """
        kind = link.kind.value

        if kind == "wikilink":
            return self._build_wikilink(link, target_path)
        elif kind == "markdown":
            return self._build_markdown_link(link, target_path)
        elif kind == "embed":
            return self._build_embed(link, target_path)
        else:
            return f"[[{target_path}]]"

    def _build_wikilink(self, link, target_path: str) -> str:
        """Build wikilink preserving alias and fragment."""
        # For wikilinks, use stem (filename without extension)
        from pathlib import Path
        stem = Path(target_path).stem

        parts = [stem]

        # Fragment (heading or block)
        if link.fragment:
            parts.append(f"#{link.fragment}")

        # Alias
        if link.alias:
            parts.insert(1, f"|{link.alias}")

        return f"[[{''.join(parts)}]]"

    def _build_markdown_link(self, link, target_path: str) -> str:
        """Build markdown link preserving text."""
        # Text is the alias or the last part of path
        text = link.alias or target_path.split('/')[-1]
        # URL encode path for markdown links
        import urllib.parse
        encoded_path = urllib.parse.quote(target_path, safe='/')
        return f"[{text}]({encoded_path})"

    def _build_embed(self, link, target_path: str) -> str:
        """Build embed preserving fragment."""
        from pathlib import Path
        stem = Path(target_path).stem
        if link.fragment:
            return f"![[{stem}#{link.fragment}]]"
        return f"![[{stem}]]"

    def apply_fixes(
        self,
        plan: FixPlan,
        dry_run: bool = True,
    ) -> tuple[list[Path], list[str]]:
        """
        Apply fixes from a plan.

        Args:
            plan: The fix plan to apply
            dry_run: If True, don't write files

        Returns:
            (list of modified files, list of errors)
        """
        modified = []
        errors = []

        # Group by file
        by_file: dict[Path, list[FixCandidate]] = {}
        for fix in plan.safe_fixes:
            if fix.source_file not in by_file:
                by_file[fix.source_file] = []
            by_file[fix.source_file].append(fix)

        for file_path, fixes in by_file.items():
            try:
                if dry_run:
                    modified.append(file_path)
                else:
                    # Read file
                    content = file_path.read_text(encoding='utf-8', errors='replace')

                    # Apply fixes (in reverse order to preserve line numbers)
                    for fix in sorted(fixes, key=lambda f: f.line, reverse=True):
                        if fix.old_text in content:
                            content = content.replace(fix.old_text, fix.new_text, 1)

                    # Write back
                    file_path.write_text(content, encoding='utf-8')
                    modified.append(file_path)

            except Exception as e:
                errors.append(f"{file_path}: {e}")

        return modified, errors

    def validate_fixes(
        self,
        original_diagnostics: list[Diagnostic],
        modified_files: list[Path],
        resolver,
    ) -> tuple[int, int]:
        """
        Validate that fixes didn't introduce new errors.

        Args:
            original_diagnostics: Diagnostics before fixes
            modified_files: Files that were modified
            resolver: Resolver instance for re-checking

        Returns:
            (new_error_count, fixed_count)
        """
        from obc.extract import extract_links
        import itertools

        fixed = 0
        new_errors = 0

        # Re-extract links from modified files
        for file_path in modified_files:
            content = file_path.read_text(encoding='utf-8', errors='replace')
            counter = itertools.count()
            links = extract_links(content, file_path, counter)

            # Re-resolve
            for link in links:
                diags = resolver.resolve_all([link])
                if diags[0].severity == "error":
                    new_errors += 1

        # Count fixed
        for diag in original_diagnostics:
            if diag.severity in ("error", "warning"):
                if diag.link.source_file not in modified_files:
                    continue
                # Check if this diagnostic is now OK
                # (simplified - full validation would re-resolve)

        return new_errors, fixed
